spring:
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: hello
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/hello
        - id: order
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        - id: inventory
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**
