spring:
  data:
    mongodb:
    #   uri: mongodb://root:generic@localhost:27017/inventorydb
        host: localhost
        port: 27017
        database: qainventorydb
        username: root
        password: generic
        authentication-database: admin
 

