spring:
  data:
    mongodb:
    #   uri: mongodb://root:generic@localhost:27017/inventorydb
        host: ${MONGO_HOST:localhost}
        port: 27017
        database: inventorydb
        username: root
        password: generic
        authentication-database: admin
 

